#!/usr/bin/env bash
# HSEOS session-end handler — Wave 4 implementation slice (W4-T4)
#
# Event:   SessionEnd
# Status:  active (replaces upstream ~/.claude/hooks/on-session-end.sh)
#
# Two-tier behaviour, gated by hseos.config.yaml second_brain.enabled:
#
#   Tier 1 (always — project-scoped):
#     - Writes a SESSION-END.md marker into
#       .hseos/runs/sessions/<session-id>/ with timestamp, branch,
#       and dirty-tree summary so a follow-up session can pick up
#       where this one stopped.
#
#   Tier 2 (only when second_brain.enabled: true):
#     - Appends a session-end line to the configured vault's
#       activity-log.md.
#     - Touches .needs-end-session flag in the vault as a reminder
#       that the explicit /end-session skill has not run yet.
#
# Authoring rules (per .agents/hooks/handlers/README.md):
#   - Idempotent: re-invoking overwrites the SESSION-END marker; the
#     activity-log line is timestamped so duplicates are visually
#     distinguishable but harmless
#   - Best-effort: never blocks; exit 0 always
#   - Project-scoped: Tier 1 writes only inside .hseos/
#   - Config-aware: Tier 2 reads second_brain.enabled + path from
#     hseos.config.yaml; absent flag/path → Tier 2 is skipped silently
#   - Fail-open: when .hseos/ is missing, exits silently
#
# Environment:
#   HSEOS_SESSION_ID — opaque session id (default: pid + day)

set -euo pipefail

PROJECT_ROOT="$(pwd)"

# Skip silently when not running in an HSEOS-installed project
if [[ ! -d "$PROJECT_ROOT/.hseos" ]]; then
  exit 0
fi

SESSION_ID="${HSEOS_SESSION_ID:-pid-$$-$(date +%Y%m%d)}"
RUN_DIR="$PROJECT_ROOT/.hseos/runs/sessions/$SESSION_ID"
MARKER="$RUN_DIR/SESSION-END.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

mkdir -p "$RUN_DIR" 2>/dev/null || exit 0

BRANCH=$(git -C "$PROJECT_ROOT" branch --show-current 2>/dev/null || echo "(unknown)")
DIRTY=$(git -C "$PROJECT_ROOT" status --short 2>/dev/null | head -10 || echo "(no working tree state)")

# Tier 1 — always: project-local SESSION-END marker
{
  printf '# Session End — %s\n\n' "$TIMESTAMP"
  printf '**Session:** `%s`\n\n' "$SESSION_ID"
  printf '**Project root:** `%s`\n\n' "$PROJECT_ROOT"
  printf '**Branch on close:** `%s`\n\n' "$BRANCH"
  printf '## Dirty working tree (top 10 entries)\n\n```\n%s\n```\n\n' "${DIRTY:-(clean)}"
  printf '_Generated by `.agents/hooks/handlers/session-end.sh`._\n'
} > "$MARKER" 2>/dev/null || true

# Tier 2 — gated: vault activity-log append when second_brain.enabled is true.
# We avoid pulling a YAML parser dependency by grep-matching the relevant
# lines in hseos.config.yaml. Both the enabled flag and the path must be
# explicit; missing or false → Tier 2 silent skip.
CONFIG="$PROJECT_ROOT/.hseos/config/hseos.config.yaml"
if [[ -f "$CONFIG" ]]; then
  ENABLED=$(grep -E '^[[:space:]]*enabled:[[:space:]]*true[[:space:]]*$' \
              <(awk '/^second_brain:/{flag=1; next} flag && /^[^[:space:]]/{flag=0} flag' "$CONFIG") \
              2>/dev/null | head -1 || true)

  if [[ -n "$ENABLED" ]]; then
    VAULT_PATH=$(awk '/^second_brain:/{flag=1; next} flag && /^[^[:space:]]/{flag=0} flag' "$CONFIG" \
                 | grep -E '^[[:space:]]*path:' | head -1 \
                 | sed -E 's/^[[:space:]]*path:[[:space:]]*//; s/[[:space:]]*$//' || true)

    if [[ -n "$VAULT_PATH" && -d "$VAULT_PATH" ]]; then
      LOG="$VAULT_PATH/_memory/activity-log.md"
      FLAG="$VAULT_PATH/_memory/.needs-end-session"

      mkdir -p "$VAULT_PATH/_memory" 2>/dev/null || true

      if [[ -f "$LOG" ]]; then
        printf '\n## [%s] session-end | %s\n' "$TIMESTAMP" "${PROJECT_ROOT##*/}" >> "$LOG" 2>/dev/null || true
      fi

      printf '%s\n' "$(date +%Y-%m-%d)" > "$FLAG" 2>/dev/null || true
    fi
  fi
fi

exit 0
