#!/usr/bin/env bash
# =============================================================================
# HSEOS Commit Message Validator
# Authority: Enterprise Constitution > execution-governance
# Usage: ./scripts/governance/validate-commit-msg.sh "<message>"
#        OR: called by .husky/commit-msg with $1 = .git/COMMIT_EDITMSG path
#        --ai-terms-only "<message>": run only the AI-mention and co-author
#        rules (used by quality-gates.sh Gate 5 so both share one vocabulary)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

pass()  { echo -e "${GREEN}[COMMIT-MSG]${NC} $*"; }
fail()  { echo -e "${RED}[COMMIT-MSG]${NC} $*"; }
warn()  { echo -e "${YELLOW}[COMMIT-MSG]${NC} $*"; }
fatal() { echo -e "${RED}[COMMIT-MSG-FATAL]${NC} $*"; exit 1; }

FAILURES=0
record_fail() { FAILURES=$((FAILURES + 1)); fail "$@"; }

AI_TERMS_ONLY=false
if [[ "${1:-}" == "--ai-terms-only" ]]; then
  AI_TERMS_ONLY=true
  shift
fi

# Get commit message — either from file path (husky) or direct arg
if [[ "${1:-}" == *.git/COMMIT_EDITMSG ]] || [[ -f "${1:-}" ]]; then
  COMMIT_MSG="$(cat "$1")"
else
  COMMIT_MSG="${1:-}"
fi

[[ -n "$COMMIT_MSG" ]] || fatal "No commit message provided"

# Strip comments and blank lines for validation
EFFECTIVE_MSG="$(echo "$COMMIT_MSG" | grep -v '^#' | sed '/^$/d')"

# =============================================================================
# Rule 1: Conventional commit format
# Format: <type>(<scope>): <description>
# Types: feat, fix, docs, style, refactor, test, chore, ci, build, perf, revert
# =============================================================================
CONVENTIONAL_PATTERN='^(feat|fix|docs|style|refactor|test|chore|ci|build|perf|revert)(\([a-z0-9_/-]+\))?: .{1,100}$'
FIRST_LINE="$(echo "$EFFECTIVE_MSG" | head -1)"

if [[ "$AI_TERMS_ONLY" == "true" ]]; then
  :  # format is not checked in --ai-terms-only mode
elif echo "$FIRST_LINE" | grep -qE "$CONVENTIONAL_PATTERN"; then
  pass "Format: conventional commit format valid"
else
  record_fail "Format: must follow '<type>(<scope>): <summary>' pattern"
  fail "  Got: ${FIRST_LINE}"
  fail "  Valid types: feat fix docs style refactor test chore ci build perf revert"
fi

# =============================================================================
# Rule 2: No AI system mentions
# =============================================================================
AI_TERMS=(
  "claude" "codex" "openai" "gpt" "chatgpt" "copilot"
  "llm" "language model" "ai-generated" "ai generated"
  "generated by" "written by ai" "assisted by"
  "anthropic" "gemini" "mistral"
  "autogenerated by" "auto-generated by" "auto generated by"
)

# Technical identifiers of tool adapters (paths and package names) are not AI
# attribution; they are removed from a lowercase copy before matching. Prose
# naming a vendor or tool stays forbidden.
ALLOWED_IDENTIFIERS=(
  ".claude-plugin" ".codex-plugin" ".claude/" ".codex/"
  "claude-code" "claude_code"
)

# Normalize before matching so look-alike characters cannot hide a term:
# NFKD (fullwidth/compatibility forms fold to ASCII, accents split off), drop
# combining marks and invisible format characters (zero-width space/joiner,
# BOM, soft hyphen, bidi marks), lowercase, then map the common Cyrillic and
# Greek confusables of Latin letters. Bounded list, core perl only; exotic
# confusables outside it are a documented residual limitation. Finally collapse
# all whitespace (including newlines) so multi-word terms cannot be split.
MSG_NORM="$(printf '%s' "$COMMIT_MSG" | perl -MUnicode::Normalize -MEncode -e '
  local $/; my $t = decode("UTF-8", <STDIN>, Encode::FB_DEFAULT);
  $t = NFKD($t);
  $t =~ s/[\p{Mn}\p{Cf}]//g;
  $t = lc($t);
  my %c = (
    "\x{0430}"=>"a","\x{0435}"=>"e","\x{043E}"=>"o","\x{0440}"=>"p","\x{0441}"=>"c",
    "\x{0443}"=>"y","\x{0445}"=>"x","\x{0456}"=>"i","\x{0458}"=>"j","\x{0455}"=>"s",
    "\x{04CF}"=>"l","\x{0501}"=>"d","\x{051B}"=>"q","\x{051D}"=>"w","\x{04BB}"=>"h",
    "\x{0432}"=>"b","\x{043D}"=>"h","\x{043A}"=>"k","\x{0442}"=>"t","\x{043C}"=>"m",
    "\x{03B1}"=>"a","\x{03B5}"=>"e","\x{03BF}"=>"o","\x{03C1}"=>"p","\x{03BD}"=>"v",
    "\x{03B9}"=>"i","\x{03BA}"=>"k","\x{03C5}"=>"u","\x{03C7}"=>"x","\x{03C4}"=>"t",
    "\x{0131}"=>"i","\x{2113}"=>"l",
  );
  my $re = join("|", map { quotemeta } keys %c);
  $t =~ s/($re)/$c{$1}/g;
  $t =~ s/[\n\t\r]/ /g; $t =~ s/ +/ /g;
  print encode("UTF-8", $t);
')"
MSG_LOWER="$MSG_NORM"

# An identifier is removed only when it stands alone: not glued to a preceding
# letter, digit or underscore (paths also not to a preceding dot), and, for
# names, not continued by a letter, digit, underscore or hyphen. Anything that
# survives falls through to the term match below.
MSG_LOWER="$(printf '%s' "$MSG_LOWER" | perl -pe '
  s{(?<![a-z0-9_.])\.(?:claude|codex)/}{ }g;
  s{(?<![a-z0-9_])(?:claude-code|claude_code|\.claude-plugin|\.codex-plugin)(?![a-z0-9_-])(?!\s+(?:co-)?(?:authored|wrote|written|generated|created|made|produced|drafted|assisted|did|helped))}{ }g;
')"
# Removing an identifier leaves a gap inside multi-word terms; close it again.
MSG_LOWER="$(printf '%s' "$MSG_LOWER" | tr -s ' ')"

# A term counts unless it sits inside a longer word made only of letters
# (gptr, controllm). Digits, underscores, hyphens and dots do not shield it, and
# a plain plural is the term itself (llms, claudes).
has_ai_term() {
  TERM="$1" perl -e '
    local $/; my $m = <STDIN>; my $t = quotemeta($ENV{TERM});
    exit(($m =~ /(?<![a-z])$t(?:s)?(?![a-z])/) ? 0 : 1);
  ' <<<"$MSG_LOWER"
}

for term in "${AI_TERMS[@]}"; do
  if has_ai_term "$term"; then
    record_fail "AI mention forbidden: found '${term}' in commit message"
  fi
done

if [[ $FAILURES -eq 0 ]]; then
  pass "AI mentions: none detected"
fi

# =============================================================================
# Rule 3: No co-author trailers
# =============================================================================
# Known trade-offs: a "co-authored-by:" with its colon is rejected anywhere in
# the message, and the identifier verb lookahead above includes generic verbs
# such as "did" and "made", so "claude-code made X" is rejected. NFKD also strips
# accents, so an accented form of a forbidden term ("Cláude") is rejected too.
# Matched anywhere in the normalized message (not only at a line start), so an
# indented, mid-line or look-alike-spelled trailer is still rejected.
if printf '%s' "$MSG_NORM" | grep -qE 'co[- ]?authored[- ]?by[[:space:]]*:'; then
  record_fail "Co-Authored-By trailer is forbidden in commit messages"
else
  pass "Co-author: no trailer found"
fi

if [[ "$AI_TERMS_ONLY" == "true" ]]; then
  [[ $FAILURES -eq 0 ]] || fatal "AI mention validation FAILED (${FAILURES} violation(s))"
  exit 0
fi

# =============================================================================
# Rule 4: Subject line length (max 100 chars)
# =============================================================================
SUBJECT_LEN="${#FIRST_LINE}"
if [[ $SUBJECT_LEN -gt 100 ]]; then
  record_fail "Subject line too long: ${SUBJECT_LEN} chars (max 100)"
else
  pass "Subject length: ${SUBJECT_LEN}/100"
fi

# =============================================================================
# Rule 5: No WIP / placeholder commits on protected branches
# =============================================================================
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
WIP_TERMS=("WIP" "wip" "fixup!" "squash!" "TODO" "[WIP]")

for term in "${WIP_TERMS[@]}"; do
  if echo "$FIRST_LINE" | grep -qF "$term"; then
    if [[ "$CURRENT_BRANCH" =~ ^(main|master|develop)$ ]]; then
      record_fail "WIP commit '${term}' forbidden on protected branch: ${CURRENT_BRANCH}"
    else
      warn "WIP commit '${term}' detected — not allowed in final PR"
    fi
  fi
done

# =============================================================================
# Result
# =============================================================================
echo ""
if [[ $FAILURES -gt 0 ]]; then
  fatal "Commit message validation FAILED (${FAILURES} violation(s))"
else
  pass "Commit message validation PASSED"
fi
