#!/usr/bin/env bash
# =============================================================================
# HSEOS Commit Message Validator
# Authority: Enterprise Constitution > execution-governance
# Usage: ./scripts/governance/validate-commit-msg.sh "<message>"
#        OR: called by .husky/commit-msg with $1 = .git/COMMIT_EDITMSG path
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

pass()  { echo -e "${GREEN}[COMMIT-MSG]${NC} $*"; }
fail()  { echo -e "${RED}[COMMIT-MSG]${NC} $*"; }
warn()  { echo -e "${YELLOW}[COMMIT-MSG]${NC} $*"; }
fatal() { echo -e "${RED}[COMMIT-MSG-FATAL]${NC} $*"; exit 1; }

FAILURES=0
record_fail() { FAILURES=$((FAILURES + 1)); fail "$@"; }

# Get commit message — either from file path (husky) or direct arg
if [[ "${1:-}" == *.git/COMMIT_EDITMSG ]] || [[ -f "${1:-}" ]]; then
  COMMIT_MSG="$(cat "$1")"
else
  COMMIT_MSG="${1:-}"
fi

[[ -n "$COMMIT_MSG" ]] || fatal "No commit message provided"

# Strip comments and blank lines for validation
EFFECTIVE_MSG="$(echo "$COMMIT_MSG" | grep -v '^#' | sed '/^$/d')"

# =============================================================================
# Rule 1: Conventional commit format
# Format: <type>(<scope>): <description>
# Types: feat, fix, docs, style, refactor, test, chore, ci, build, perf, revert
# =============================================================================
CONVENTIONAL_PATTERN='^(feat|fix|docs|style|refactor|test|chore|ci|build|perf|revert)(\([a-z0-9_/-]+\))?: .{1,100}$'
FIRST_LINE="$(echo "$EFFECTIVE_MSG" | head -1)"

if echo "$FIRST_LINE" | grep -qE "$CONVENTIONAL_PATTERN"; then
  pass "Format: conventional commit format valid"
else
  record_fail "Format: must follow '<type>(<scope>): <summary>' pattern"
  fail "  Got: ${FIRST_LINE}"
  fail "  Valid types: feat fix docs style refactor test chore ci build perf revert"
fi

# =============================================================================
# Rule 2: No AI system mentions
# =============================================================================
AI_TERMS=(
  "claude" "codex" "openai" "gpt" "chatgpt" "copilot"
  "llm" "language model" "ai-generated" "ai generated"
  "generated by" "written by ai" "assisted by"
  "anthropic" "gemini" "mistral"
)

MSG_LOWER="$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')"
for term in "${AI_TERMS[@]}"; do
  if echo "$MSG_LOWER" | grep -q "$term"; then
    record_fail "AI mention forbidden: found '${term}' in commit message"
  fi
done

if [[ $FAILURES -eq 0 ]]; then
  pass "AI mentions: none detected"
fi

# =============================================================================
# Rule 3: No co-author trailers
# =============================================================================
if echo "$COMMIT_MSG" | grep -iqE '^Co-Authored-By:|^Co-authored-by:'; then
  record_fail "Co-Authored-By trailer is forbidden in commit messages"
else
  pass "Co-author: no trailer found"
fi

# =============================================================================
# Rule 4: Subject line length (max 100 chars)
# =============================================================================
SUBJECT_LEN="${#FIRST_LINE}"
if [[ $SUBJECT_LEN -gt 100 ]]; then
  record_fail "Subject line too long: ${SUBJECT_LEN} chars (max 100)"
else
  pass "Subject length: ${SUBJECT_LEN}/100"
fi

# =============================================================================
# Rule 5: No WIP / placeholder commits on protected branches
# =============================================================================
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')"
WIP_TERMS=("WIP" "wip" "fixup!" "squash!" "TODO" "[WIP]")

for term in "${WIP_TERMS[@]}"; do
  if echo "$FIRST_LINE" | grep -qF "$term"; then
    if [[ "$CURRENT_BRANCH" =~ ^(main|master|develop)$ ]]; then
      record_fail "WIP commit '${term}' forbidden on protected branch: ${CURRENT_BRANCH}"
    else
      warn "WIP commit '${term}' detected — not allowed in final PR"
    fi
  fi
done

# =============================================================================
# Result
# =============================================================================
echo ""
if [[ $FAILURES -gt 0 ]]; then
  fatal "Commit message validation FAILED (${FAILURES} violation(s))"
else
  pass "Commit message validation PASSED"
fi
