'use strict';

/**
 * Hooks source.
 *
 * Canonical source: .enterprise/governance/hooks/registry.yaml (+ handlers/).
 * Compatibility fallbacks (in order): the compiled .agents/hooks/registry.yaml
 * of the target, then of the source root, then a legacy hooks.json bootstrap.
 *
 * When sourcePath ends with .yaml  → treat as neutral registry (preferred)
 * When sourcePath ends with .json  → read legacy hooks.json and convert (bootstrap only)
 * When sourcePath is null/absent   → write empty registry
 *
 * `syncHandlers` copies handler scripts from the enterprise source into
 * .agents/hooks/handlers/ (CRLF-normalized, mode preserved) and returns
 * hash-pin entries for the manifest, mirroring how skills are pinned.
 */

const path = require('node:path');
const fs = require('fs-extra');
const yaml = require('yaml');
const { slug } = require('../lib/slug');
const { hash } = require('../lib/hash');

async function writeHookRegistry(root, sourcePath, _legacyFallback, agentsDirName = '.agents') {
  const outputDir = path.join(root, agentsDirName, 'hooks');
  await fs.ensureDir(outputDir);

  let hooks = [];

  let parsedRegistry = {};

  if (sourcePath && (await fs.pathExists(sourcePath))) {
    if (sourcePath.endsWith('.yaml') || sourcePath.endsWith('.yml')) {
      parsedRegistry = yaml.parse(await fs.readFile(sourcePath, 'utf8')) || {};
      hooks = parsedRegistry.hooks || [];
    } else {
      // Legacy bootstrap: convert hooks.json → neutral registry entries
      const parsed = JSON.parse(await fs.readFile(sourcePath, 'utf8'));
      for (const [event, groups] of Object.entries(parsed.hooks || {})) {
        for (const group of groups || []) {
          for (const hook of group.hooks || []) {
            hooks.push({
              id: slug(`${event}-${group.matcher || 'all'}-${hook.description || hook.command}`),
              event,
              matcher: group.matcher || '*',
              type: hook.type || 'command',
              command: hook.command,
              timeout: hook.timeout || null,
              blocking: event === 'PreToolUse',
              status: 'active',
              description: hook.description || '',
              platform_support: ['claude-code'],
              fallback: 'Use repository scripts or quality gates when the target platform has no native hook event.',
            });
          }
        }
      }
    }
  }

  const registry = {
    version: '1.1',
    schema_version: parsedRegistry.schema_version || '1.0',
    source: sourcePath ? path.relative(root, sourcePath).replaceAll(path.sep, '/') : 'none',
    handlers_dir: parsedRegistry.handlers_dir || `${agentsDirName}/hooks/handlers`,
    hooks,
  };

  const header = [
    '# Generated by `hseos agent-core compile` — DO NOT EDIT.',
    `# Canonical source: ${registry.source} (edit hooks and handlers there).`,
    '# `status` semantics (enforced by the platform adapter emitters):',
    '#   active (or omitted)  -- compiled into platform adapters (.claude/hooks.json, ...)',
    '#   any other value (pending / inactive / deprecated) -- kept in the registry for',
    '#   migration/audit, never emitted to adapters.',
    '',
  ].join('\n');

  await fs.writeFile(path.join(outputDir, 'registry.yaml'), header + yaml.stringify(registry, { lineWidth: 0 }), 'utf8');
  return hooks;
}

async function syncHandlers(root, sourceHandlersDir, agentsDirName = '.agents') {
  if (!sourceHandlersDir || !(await fs.pathExists(sourceHandlersDir))) return [];

  const outputDir = path.join(root, agentsDirName, 'hooks', 'handlers');
  await fs.ensureDir(outputDir);

  const handlers = [];
  const names = (await fs.readdir(sourceHandlersDir)).filter((name) => !name.startsWith('.')).sort();
  for (const name of names) {
    const sourceFile = path.join(sourceHandlersDir, name);
    const stat = await fs.stat(sourceFile);
    if (!stat.isFile()) continue;

    const content = (await fs.readFile(sourceFile, 'utf8')).replaceAll('\r\n', '\n');
    const outputFile = path.join(outputDir, name);
    await fs.writeFile(outputFile, content, { mode: stat.mode });

    handlers.push({
      file: `${agentsDirName}/hooks/handlers/${name}`,
      source: path.relative(root, sourceFile).replaceAll(path.sep, '/'),
      sha256: hash(content),
    });
  }
  return handlers;
}

module.exports = { syncHandlers, writeHookRegistry };
