'use strict';

/**
 * AGENTS.md emitter.
 *
 * Several adapters (Codex, future LF AAIF tools) treat AGENTS.md as the
 * project-root entry point for agent rules. The agent-core compiler writes
 * its vendor-neutral source to .agents/instructions/PROJECT.md and expects
 * platform adapter files at the root to point at it.
 *
 * This module emits a minimal AGENTS.md stub when none exists. If the project
 * already has an AGENTS.md (org-authored, customised, or carried in from a
 * prior install) we leave it alone — agent rules are governance, never to be
 * overwritten silently.
 */

const path = require('node:path');
const fs = require('fs-extra');

const AGENTS_MD = 'AGENTS.md';

function buildAgentsMdContent(agentsDirName = '.agents') {
  const dir = agentsDirName;
  return `# AGENTS.md

> HSEOS agent entry point. This file is the platform adapter for tools that
> read \`AGENTS.md\` at the project root (Codex, LF AAIF, and similar).
>
> Authoritative, vendor-neutral source: \`${dir}/instructions/PROJECT.md\`.

## Instruction cascade

1. Enterprise constitution — \`.enterprise/.specs/constitution/Enterprise-Constitution.md\`
2. Project-neutral agent rules — \`${dir}/instructions/PROJECT.md\` and \`${dir}/manifest.yaml\`
3. Platform adapter — this file (\`AGENTS.md\`), \`CLAUDE.md\`, etc.
4. Agent authority — \`.enterprise/agents/<code>/authority.md\`
5. Triggered skill — \`${dir}/skills/<skill>/SKILL.md\`
6. User instruction in the active conversation

If two instructions conflict, stop and ask for a human decision. Do not
average standards.

## Local rules

- Never commit directly to \`main\`, \`master\`, or \`develop\`.
- Never add AI attribution or co-author trailers to commits.
- Run repository quality gates before any commit (\`scripts/governance/quality-gates.sh\` when present).
- Treat \`${dir}/hooks/registry.yaml\` as the neutral hook registry. Platform-specific hook files are compiled adapters.

## Generated by

\`npx hseos install\` — re-running install will not overwrite this file. To
regenerate from scratch, delete the file first.
`;
}

async function writeAgentsMdAdapter(root, { agentsDirName = '.agents' } = {}) {
  const target = path.join(root, AGENTS_MD);
  if (await fs.pathExists(target)) {
    return { path: target, written: false, reason: 'preserved-existing' };
  }
  await fs.writeFile(target, buildAgentsMdContent(agentsDirName), 'utf8');
  return { path: target, written: true };
}

module.exports = { writeAgentsMdAdapter, buildAgentsMdContent, AGENTS_MD };
