'use strict';

/**
 * CLAUDE.md emitter.
 *
 * Claude Code reads CLAUDE.md as the repository entry point. HSEOS keeps durable
 * agent rules in AGENTS.md (the vendor-neutral entrypoint); CLAUDE.md is a thin
 * compatibility pointer so Claude Code is routed to the same governance source.
 *
 * The manifest declares `adapters.claude_code.entrypoint: CLAUDE.md`. Without
 * this emitter a fresh install leaves Claude Code with no root entrypoint
 * pointing at AGENTS.md. This mirrors the AGENTS.md adapter.
 *
 * The emitted file opens with the `@AGENTS.md` import. ADR-0006 makes AGENTS.md the
 * canonical entrypoint and CLAUDE.md a compatibility pointer; the import is how Claude
 * Code honours that pointer, since without it the runtime ignores AGENTS.md entirely.
 *
 * Behaviour:
 *   - Only emits when the `claude-code` platform is active (CLAUDE.md is a
 *     Claude-Code-specific entrypoint, unlike the platform-neutral AGENTS.md).
 *   - Never overwrites an existing CLAUDE.md (org-authored, customised, or
 *     carried from a prior install). Agent rules are governance, not generated
 *     content. This also respects the claude-md-guard hook, which routes
 *     durable rules to AGENTS.md.
 */

const path = require('node:path');
const fs = require('fs-extra');

const CLAUDE_MD = 'CLAUDE.md';

function buildClaudeMdContent() {
  // The `@AGENTS.md` import MUST be the first line. With a CLAUDE.md present the
  // runtime loads it and ignores AGENTS.md by default — prose asking the agent to
  // "read AGENTS.md" does not substitute for the import, because the agent never
  // sees the instruction it is being asked to obey. Emitting the prose-only form
  // broke the ADR-0006 contract (CLAUDE.md as a pointer to AGENTS.md) in every
  // repository scaffolded by `hseos install`.
  return `@AGENTS.md

# CLAUDE.md — Compatibility Pointer

> Claude Code reads this file as the repository entry point. HSEOS keeps durable
> agent rules in \`AGENTS.md\`, imported on the first line above.
>
> **Do not remove the import.** With a \`CLAUDE.md\` present the runtime ignores
> \`AGENTS.md\` by default; a sentence asking to "read AGENTS.md" is not a
> substitute for the import.

Do not write durable instructions in \`CLAUDE.md\`. If a rule needs to change,
update \`AGENTS.md\` instead.

## Generated by

\`npx hseos install\` — re-running install will not overwrite this file. To
regenerate from scratch, delete the file first.
`;
}

async function writeClaudeMdAdapter(root, platforms = []) {
  const target = path.join(root, CLAUDE_MD);
  if (!platforms.includes('claude-code')) {
    return { path: target, written: false, reason: 'claude-code-not-selected' };
  }
  if (await fs.pathExists(target)) {
    return { path: target, written: false, reason: 'preserved-existing' };
  }
  await fs.writeFile(target, buildClaudeMdContent(), 'utf8');
  return { path: target, written: true };
}

module.exports = { writeClaudeMdAdapter, buildClaudeMdContent, CLAUDE_MD };
