'use strict';

/**
 * CLAUDE.md emitter.
 *
 * Claude Code reads CLAUDE.md as the repository entry point. HSEOS keeps durable
 * agent rules in AGENTS.md (the vendor-neutral entrypoint); CLAUDE.md is a thin
 * compatibility pointer so Claude Code is routed to the same governance source.
 *
 * The manifest declares `adapters.claude_code.entrypoint: CLAUDE.md`, but the
 * Claude Code adapter only emits `.claude/hooks.json` and `.claude/commands`.
 * Without this emitter a fresh install leaves Claude Code with no root
 * entrypoint pointing at AGENTS.md. This mirrors the AGENTS.md adapter.
 *
 * Behaviour:
 *   - Only emits when the `claude-code` platform is active (CLAUDE.md is a
 *     Claude-Code-specific entrypoint, unlike the platform-neutral AGENTS.md).
 *   - Never overwrites an existing CLAUDE.md (org-authored, customised, or
 *     carried from a prior install). Agent rules are governance, not generated
 *     content. This also respects the claude-md-guard hook, which routes
 *     durable rules to AGENTS.md.
 */

const path = require('node:path');
const fs = require('fs-extra');

const CLAUDE_MD = 'CLAUDE.md';

function buildClaudeMdContent() {
  return `# CLAUDE.md — Compatibility Pointer

> Claude Code reads this file as the repository entry point. HSEOS keeps durable
> agent rules in \`AGENTS.md\`; this file only routes there.

Read \`AGENTS.md\` before any action in this repository. \`AGENTS.md\` is the
canonical place for agent rules, directives, governance, and task execution
policy.

Do not write durable instructions in \`CLAUDE.md\`. If a rule needs to change,
update \`AGENTS.md\` instead.

## Generated by

\`npx hseos install\` — re-running install will not overwrite this file. To
regenerate from scratch, delete the file first.
`;
}

async function writeClaudeMdAdapter(root, platforms = []) {
  const target = path.join(root, CLAUDE_MD);
  if (!platforms.includes('claude-code')) {
    return { path: target, written: false, reason: 'claude-code-not-selected' };
  }
  if (await fs.pathExists(target)) {
    return { path: target, written: false, reason: 'preserved-existing' };
  }
  await fs.writeFile(target, buildClaudeMdContent(), 'utf8');
  return { path: target, written: true };
}

module.exports = { writeClaudeMdAdapter, buildClaudeMdContent, CLAUDE_MD };
