'use strict';

/**
 * Codex platform adapter.
 *
 * Codex reads AGENTS.md and project skills from .agents/skills. Its project
 * config surface is .codex/config.toml, including MCP server declarations.
 * Codex CLI does not currently consume Claude-style hook JSON, so hook intent is
 * emitted as metadata for audit/fallback while the portable handler scripts stay
 * canonical under .agents/hooks/handlers/.
 */

const path = require('node:path');
const fs = require('fs-extra');
const yaml = require('yaml');

const CODEX_DIR = '.codex';
const CONFIG_PATH = path.join(CODEX_DIR, 'config.toml');
const HOOKS_META_PATH = path.join(CODEX_DIR, 'hseos-hooks.json');

function tomlString(value) {
  return JSON.stringify(String(value));
}

function tomlArray(values) {
  return `[${values.map((value) => tomlString(value)).join(', ')}]`;
}

function normalizeServerId(id) {
  return String(id || '').trim();
}

function resolveServerCommand(server) {
  if (server.command) {
    return { command: server.command, args: server.args || [] };
  }

  const resolver = Array.isArray(server.binary_resolver) ? server.binary_resolver[0] : null;
  if (resolver?.runtime === 'node' && resolver.path) {
    return { command: 'node', args: [resolver.path] };
  }

  if (server.runtime === 'npx') {
    return { command: 'npx', args: server.args || (server.package ? ['-y', server.package] : []) };
  }

  if (server.package) {
    return { command: server.runtime || 'npx', args: server.args || ['-y', server.package] };
  }

  return null;
}

async function loadMcpServers(root, agentsDirName = '.agents') {
  const registryPath = path.join(root, agentsDirName, 'mcp', 'registry.yaml');
  if (!(await fs.pathExists(registryPath))) return [];

  const registry = yaml.parse(await fs.readFile(registryPath, 'utf8')) || {};
  const bundleEntries = Object.entries(registry.bundles || {});
  const servers = [];

  for (const [, bundle] of bundleEntries) {
    if (!bundle?.required) continue;
    const bundlePath = path.join(path.dirname(registryPath), bundle.file || '');
    if (!(await fs.pathExists(bundlePath))) continue;

    const bundleRaw = yaml.parse(await fs.readFile(bundlePath, 'utf8')) || {};
    for (const server of bundleRaw.servers || []) {
      const id = normalizeServerId(server.id);
      const commandSpec = resolveServerCommand(server);
      if (!id || !commandSpec?.command) continue;
      servers.push({
        id,
        command: commandSpec.command,
        args: commandSpec.args || [],
        env: server.env || {},
      });
    }
  }

  return servers;
}

function buildCodexConfigToml({ mcpServers = [] }) {
  const lines = ['# Generated by hseos agent-core compile. Edit .agents/* sources instead.', '', '[features]', 'rmcp_client = true', ''];

  for (const server of mcpServers) {
    const serverLines = [`[mcp_servers.${tomlString(server.id)}]`, `command = ${tomlString(server.command)}`];
    if (server.args.length > 0) {
      serverLines.push(`args = ${tomlArray(server.args)}`);
    }
    serverLines.push('enabled = true', 'startup_timeout_sec = 20');
    lines.push(...serverLines);

    const envEntries = Object.entries(server.env || {});
    if (envEntries.length > 0) {
      lines.push('', `[mcp_servers.${tomlString(server.id)}.env]`, ...envEntries.map(([key, value]) => `${key} = ${tomlString(value)}`));
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function buildCodexHooksMeta(hooks) {
  const activeHooks = hooks.filter((hook) => !hook.status || hook.status === 'active');
  return {
    notice: 'Codex does not consume Claude hook JSON. HSEOS keeps hook scripts portable and records intent here for audit/manual fallback.',
    hooks: activeHooks.map((hook) => ({
      id: hook.id,
      event: hook.event,
      matcher: hook.matcher,
      command: hook.command,
      blocking: hook.blocking,
      description: hook.description,
      fallback: hook.fallback,
      codex_equivalent: 'portable-handler-script',
    })),
  };
}

async function writeCodexAdapter(root, hooks, platforms) {
  if (!platforms.includes('codex')) return;

  const codexDir = path.join(root, CODEX_DIR);
  await fs.ensureDir(codexDir);

  const mcpServers = await loadMcpServers(root);
  await fs.writeFile(path.join(root, CONFIG_PATH), buildCodexConfigToml({ mcpServers }), 'utf8');

  await fs.writeFile(path.join(root, HOOKS_META_PATH), JSON.stringify(buildCodexHooksMeta(hooks), null, 2), 'utf8');
}

class CodexAdapter {
  static get id() {
    return 'codex';
  }

  static get version() {
    return '1.0';
  }

  static get capabilities() {
    return ['agent_skills', 'mcp_stdio', 'hooks_metadata'];
  }

  async validate() {
    return { ok: true, warnings: [], errors: [] };
  }

  async emit(sources, outputDir) {
    await fs.ensureDir(path.join(outputDir, CODEX_DIR));
    await fs.writeFile(
      path.join(outputDir, CONFIG_PATH),
      buildCodexConfigToml({
        mcpServers: sources.mcpServers || [],
      }),
      'utf8',
    );
    await fs.writeFile(path.join(outputDir, HOOKS_META_PATH), JSON.stringify(buildCodexHooksMeta(sources.hooks || []), null, 2), 'utf8');
  }

  async verify(outputDir) {
    const configExists = await fs.pathExists(path.join(outputDir, CONFIG_PATH));
    const hooksMetaExists = await fs.pathExists(path.join(outputDir, HOOKS_META_PATH));
    const drift = [];
    if (!configExists) drift.push(`${CONFIG_PATH} missing - run compile`);
    if (!hooksMetaExists) drift.push(`${HOOKS_META_PATH} missing - run compile`);
    return { ok: drift.length === 0, drift };
  }

  async clean(outputDir) {
    const removed = [];
    for (const relativePath of [CONFIG_PATH, HOOKS_META_PATH]) {
      const target = path.join(outputDir, relativePath);
      if (await fs.pathExists(target)) {
        await fs.remove(target);
        removed.push(relativePath);
      }
    }
    return { removed };
  }

  mapHookEvent() {
    return null;
  }

  mapToolName(neutralName) {
    return neutralName;
  }

  resolvePath(neutralPath) {
    return neutralPath.replace(/^\.claude\//, '.codex/');
  }
}

module.exports = CodexAdapter;
module.exports.writeCodexAdapter = writeCodexAdapter;
module.exports.buildCodexConfigToml = buildCodexConfigToml;
module.exports.buildCodexHooksMeta = buildCodexHooksMeta;
module.exports.loadMcpServers = loadMcpServers;
