#!/usr/bin/env bash
# HSEOS pre-compact handler — Wave 4 implementation slice (W4-T2)
#
# Event:   PreCompact
# Status:  active (replaces upstream ~/.claude/hooks/on-pre-compact.sh)
#
# Snapshots project-local context immediately before the agent
# compacts its conversation, so a follow-up session can recover the
# critical state (cwd, branch, recent commits, open work-tree edits,
# any user-authored pre-compact notes).
#
# Authoring rules (per .agents/hooks/handlers/README.md):
#   - Idempotent: re-running overwrites the latest snapshot for the
#     current session id; never appends silently
#   - Best-effort: never blocks the triggering action; exit 0 always
#   - Project-scoped: writes only into .hseos/runs/sessions/
#   - Config-aware: vault writes deferred to session-end.sh when
#     second_brain.enabled is true; this handler is project-only
#   - Fail-open: if .hseos/ does not exist (project not installed),
#     the handler exits 0 without producing files
#
# Environment:
#   HSEOS_SESSION_ID     — opaque session id (default: pid + timestamp)
#   HSEOS_PRE_COMPACT_NOTES — project-relative path to user-authored
#                             notes file to preserve in the snapshot

set -euo pipefail

PROJECT_ROOT="$(pwd)"

# Skip silently when not running in an HSEOS-installed project
if [[ ! -d "$PROJECT_ROOT/.hseos" ]]; then
  exit 0
fi

SESSION_ID="${HSEOS_SESSION_ID:-pid-$$-$(date +%s)}"
RUN_DIR="$PROJECT_ROOT/.hseos/runs/sessions/$SESSION_ID"
SNAPSHOT="$RUN_DIR/PRE-COMPACT.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

mkdir -p "$RUN_DIR" 2>/dev/null || exit 0

# Gather project context — each step best-effort, never aborts the snapshot.
BRANCH=$(git -C "$PROJECT_ROOT" branch --show-current 2>/dev/null || echo "(unknown)")
RECENT_COMMITS=$(git -C "$PROJECT_ROOT" log --oneline -5 2>/dev/null || echo "(no git history)")
DIRTY_FILES=$(git -C "$PROJECT_ROOT" status --short 2>/dev/null | head -20 || echo "(no working tree state)")

NOTES_PATH="${HSEOS_PRE_COMPACT_NOTES:-$RUN_DIR/.pre-compact-notes.md}"
USER_NOTES=""
if [[ -f "$NOTES_PATH" ]]; then
  USER_NOTES=$(cat "$NOTES_PATH" 2>/dev/null || echo "")
fi

{
  printf '# Pre-Compact Snapshot — %s\n\n' "$TIMESTAMP"
  printf '**Session:** `%s`\n\n' "$SESSION_ID"
  printf '**Project root:** `%s`\n\n' "$PROJECT_ROOT"
  printf '**Branch:** `%s`\n\n' "$BRANCH"

  printf '## Recent commits (HEAD~5)\n\n```\n%s\n```\n\n' "$RECENT_COMMITS"

  printf '## Dirty working tree (top 20 entries)\n\n```\n%s\n```\n\n' "${DIRTY_FILES:-(clean)}"

  if [[ -n "$USER_NOTES" ]]; then
    printf '## User-authored pre-compact notes\n\n%s\n\n' "$USER_NOTES"
  fi

  printf '_Generated by `.agents/hooks/handlers/pre-compact.sh`. The follow-up '
  printf 'session may load this snapshot via `hseos session resume %s`._\n' "$SESSION_ID"
} > "$SNAPSHOT" 2>/dev/null || true

# Remove the consumed user notes so the next compact does not re-include them
if [[ -f "$NOTES_PATH" && "$NOTES_PATH" != "$SNAPSHOT" ]]; then
  rm -f "$NOTES_PATH" 2>/dev/null || true
fi

exit 0
